pipeline {
  agent {
    docker {
      image 'node:alpine3.12'
    }
  }

  stages {
    stage('Verify') {
      steps {
        sh '''
        node --version
        npm version
        '''
        sh 'printenv | sort'
      }
    }

    stage('Build') {
      steps {
        dir("$WORKSPACE/03/solution") {
          sh '''
          npm install
          npm run build
          '''
        }
      }
    }

    stage('Tests') {
      steps {
        dir("$WORKSPACE/03/solution") {
          sh 'npm test'
        }
      }
    }
  }
}
